from pathlib import Path
from munl.settings import DEFAULT_DEVICE
from munl.paths import ARTIFACTS_PATH, DATA_PATH, FIXED_SPLITS_PATH, MODEL_INITIALIZATIONS_PATH


DEFAULT_VAL_RATIO = 0.15
DEFAULT_FORGET_RATIO = 0.10
